### ISSUE TITLE
Doesn't work in laravel-mix 6

### ISSUE THREAD

**Issue by Fady-Behnan** [johnwilhite/mix-env-file#2]
I recently upgraded to mix 6 and this package stopped working. It is giving me the following error:

```
Module not found: Error: Can't resolve 'ENV_FILE=./.env.test'
```

**Comment by maxxwv** [comment]
What was the solution? I'm having the same problem.

**Comment by maxxwv** [comment]
For anyone else having an issue, I've worked around it by just naming my file `.env` and accessing the variable directly through `process.env.VARIABLE_NAME` in webpack.mix.js. Set up "dev": "mix" as a script in package.json and npm run dev - works as expected.

**Comment by merijnponzo** [comment]
I added this for building or watching different environments and it works

```
 "watch": "mix watch --hot",
    "dev": "NODE_ENV=development ENV_FILE=.env.development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js",
    "test": "NODE_ENV=production ENV_FILE=.env.staging node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js",
    "build": "NODE_ENV=production ENV_FILE=.env.production node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js",
```

within my laravel mix:
```
const mix = require("laravel-mix");
require("mix-env-file");
mix.env(process.env.ENV_FILE);
console.log(process.env.MIX_APP_HOST);
```

3 .env files:

.env  ( this is for development )
.env.production
.env.staging
